name: islamicnoteapp
description: "A new Flutter project."
publish_to: 'none' # jangan publish ke pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.1
  http: ^0.13.5
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_secure_storage: ^10.0.0

fonts:
  - family: Arabic
    fonts:
      - asset: assets/fonts/Amiri-Regular.ttf


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  
  
  assets:
   - assets/data/doa_dataset.json
